<a href="https://colab.research.google.com/github/buddhini81/learning-python/blob/main/NumpyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np

#Create a 3×3 matrix (a 2D array) named A where the elements are the numbers 1 through 9.
A = np.arange(1, 10).reshape(3, 3)
print(A)

#Create a 2×4 matrix named B filled entirely with the value 5.
B = np.full((2, 4), 5)
print(B)

#Find the shape, number of dimensions (ndim), and total number of elements (size) for both matrix A and matrix B.
print(f"A shape: {A.shape}, ndim: {A.ndim}, size: {A.size}")
print(f"B shape: {B.shape}, ndim: {B.ndim}, size: {B.size}")

#Create a 4×4 identity matrix named I.
#I = np.eye(4)
I = np.identity(4)
print(I)

#Extract the element in the second row and third column of matrix A.
print(A[1,2])

#Extract the entire second column of matrix A.
print(A[:,1])

#Extract the sub-matrix formed by the first two rows and the last two columns of matrix A.
X = A[:2,1:]
print(X)

#Change the value in the top-left corner (row 0, column 0) of matrix A to 100.
A[0,0] = 100
print(A)

#Create a second 3×3 matrix named C where the elements are the squares of the elements in matrix A.
#C = np.square(A).reshape(3,3)
C = A**2
print(C)

#Calculate the element-wise sum of matrix A and matrix C.
print(A + C)

#Perform the dot product (matrix multiplication) of matrix A and a 3×1 column vector v = [1, 2, 3]. Hint: Ensure v is correctly shaped for the multiplication.
v = np.array([1, 2, 3]).reshape(3 , 1)
print(np.dot(A, v))

#Calculate the transpose of matrix A.(converting its rows into columns and its columns into rows)
#A = A.transpose()
A = A.T
print(A)

#Calculate the determinant of matrix A
A_original = np.arange(1, 10).reshape(3, 3)
det_A = np.linalg.det(A_original) # Should be very close to 0
print(det_A)

#Reshape matrix A (currently 3×3) into a 1×9 array.
A_array = A.reshape(1,9)
print(A_array)

#Flatten matrix A into a 1D array.
#A_array2 = A.reshape(1,A.size)
A_array2 = A.flatten() # or A.ravel()
print(A_array2)

#Stack matrix B (the 2×4 matrix) vertically with a 1×4 array of zeros. What is the shape of the resulting matrix?
zeros_row = np.zeros((1, 4))
B_stacked = np.vstack((B, zeros_row))
print(B_stacked)
# Shape of B_stacked is (3, 4)

#Split matrix A (the 3×3 matrix) horizontally into three 3×1 arrays.
A_split = np.hsplit(A, 3) # Returns a list of 3 arrays
print(A_split)

#Find the maximum value in the entire matrix A.
print(f"MAX: {A.max()}")

#Calculate the mean of all elements in matrix A.
print(f"MEAN: {A.mean()}")

#Calculate the sum of each row in matrix A. (axis=1)
row_sums = A.sum(axis=1)
print(f"ROW SUM: {row_sums}")

#Find the minimum value for each column in matrix A. (axis=0)
col_mins = A.min(axis=0)
print(f"COL MIN: {col_mins}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 5 5 5]
 [5 5 5 5]]
A shape: (3, 3), ndim: 2, size: 9
B shape: (2, 4), ndim: 2, size: 8
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
6
[2 5 8]
[[2 3]
 [5 6]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[10000     4     9]
 [   16    25    36]
 [   49    64    81]]
[[10100     6    12]
 [   20    30    42]
 [   56    72    90]]
[[113]
 [ 32]
 [ 50]]
[[100   4   7]
 [  2   5   8]
 [  3   6   9]]
0.0
[[100   4   7   2   5   8   3   6   9]]
[100   4   7   2   5   8   3   6   9]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [0. 0. 0. 0.]]
[array([[100],
       [  2],
       [  3]]), array([[4],
       [5],
       [6]]), array([[7],
       [8],
       [9]])]
MAX: 100
MEAN: 16.0
ROW SUM: [111  15  18]
COL MIN: [2 4 7]
