<a href="https://colab.research.google.com/github/buddhini81/learning-python/blob/main/UsingNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Create Arrays

temperatures = np.array([20,22,25,27,21,23,30,26,24,28])
sales = np.array([15,20,35,45,18,25,60,40,30,50])

print(temperatures)
print(sales)

[20 22 25 27 21 23 30 26 24 28]
[15 20 35 45 18 25 60 40 30 50]


In [ ]:
#Calculate Statistics
avg_temp = temperatures.mean()
print(avg_temp)

max_sales = sales.max()
print(max_sales)


24.6
60


In [ ]:
#Reshape
data_matrix = np.column_stack((temperatures,sales))

print(data_matrix)

[[20 15]
 [22 20]
 [25 35]
 [27 45]
 [21 18]
 [23 25]
 [30 60]
 [26 40]
 [24 30]
 [28 50]]


In [ ]:
#boolean indexing

mask = sales > 30

temp_on_high_sales_days = temperatures[mask]

print(temp_on_high_sales_days)

mask2 = temperatures > 25
sales_on_hot_days = sales[mask2]
print(sales_on_hot_days)

x = data_matrix[(mask2) & (mask)]
print(x)

[25 27 30 26 28]
[45 60 40 50]
[[27 45]
 [30 60]
 [26 40]
 [28 50]]


In [ ]:
#Data Generation and Initial Calculations
#Create a NumPy array named closing_prices containing 20 random floating-point numbers between 100.0 and 150.0. (Hint: Use np.random.uniform).
closing_prices = np.random.uniform(100.0, 150.0, 20)

print(closing_prices)

#Calculate the daily price change (return) by subtracting yesterday's price from today's price. Store this in an array called daily_returns.
daily_returns = np.diff(closing_prices)
print(daily_returns)

#Calculate the cumulative sum of the daily_returns array and store it in cumulative_change
cumulative_change = np.cumsum(daily_returns)
print(cumulative_change)

[133.74074289 140.63601852 106.37860709 145.55742025 123.00061551
 114.08889039 125.76637837 128.67926582 127.85326443 135.95110602
 136.05561543 139.38385441 127.29529188 110.76465799 109.03165247
 127.2659866  115.06320703 136.21416307 125.45982767 101.38264384]
[  6.89527564 -34.25741143  39.17881315 -22.55680473  -8.91172513
  11.67748799   2.91288745  -0.8260014    8.09784159   0.10450941
   3.32823898 -12.08856253 -16.53063389  -1.73300553  18.23433413
 -12.20277957  21.15095604 -10.75433539 -24.07718383]
[  6.89527564 -27.36213579  11.81667736 -10.74012737 -19.6518525
  -7.97436451  -5.06147706  -5.88747846   2.21036313   2.31487254
   5.64311152  -6.445451   -22.97608489 -24.70909042  -6.47475629
 -18.67753586   2.47342018  -8.28091521 -32.35809905]


In [ ]:
#Advanced Indexing and Analysis
#Use boolean indexing on the daily_returns array to find out how many days the stock price increased (i.e., the return was positive).

#method 1
positive_days = [r for r in daily_returns if r > 0]

print(len(positive_days))

#method 2
num_positive_days = (daily_returns > 0).sum()

print(num_positive_days)

#Find the indices (positions) of the top 5 largest positive daily returns.

# np.argsort returns indices sorted by value (ascending)
# [-5:] gets the last 5 indices (the largest values)
# [::-1] reverses that slice to show them from largest to smallest return
top_5_indices = np.argsort(daily_returns)[-5:][::-1]
top_five_largest_positive_gains = daily_returns[top_5_indices]

print(top_five_largest_positive_gains)

#Use the indices from the daily_returns array to find the closing price on the day before the single largest negative drop (i.e., the index of the minimum value in daily_returns)
worst_day_index = np.argmin(daily_returns)
price_before_worst_day = closing_prices[worst_day_index]

print(price_before_worst_day)

9
9
[39.17881315 21.15095604 18.23433413 11.67748799  8.09784159]
140.63601852178456


In [6]:
import numpy as np

#Create a 1×5 array filled with zeros.
array1 = np.zeros(5)
array1

#Create a 3×3 array filled with ones.
array2 = np.ones((3,3))
array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])